name: Build / Release

on:
  push:
    branches: [ "main" ]
  create:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: docker://retcon85/toolchain-sms:1.0
      env:
        PROJECTNAME: my-project-name-v${{ github.ref_name }}
      with:
        args: |
          "make clean all"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: roms
        path: build/*.sms
        if-no-files-found: error

  release:
    if: ${{ github.event_name == 'create' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: roms
    - name: Release
      if: ${{ github.event_name == 'create' }}
      # if release already exists, attach the output artifacts to it
      # else try to create a release with a discussion post (will fail if discussion not enabled)
      # else try to create a release without a discussion post
      run: |
        gh release upload ${{ github.ref_name }} *.sms --clobber || \
        gh release create ${{ github.ref_name }} --generate-notes --title '${{ github.repository }} v${{ github.ref_name }}' --discussion-category 'Announcements' *.sms || \
        gh release create ${{ github.ref_name }} --generate-notes --title '${{ github.repository }} v${{ github.ref_name }}' *.sms
      env:
        GH_TOKEN: ${{ github.token }}
